#!/usr/bin/env python3
"""Converts noaa_2026_raw.json (NOAA CO-OPS hilo predictions for La Jolla,
station 9410230) into a compact C array for embedding in
Giga_YH_Dashboard_Unit2.ino. Each event: day-of-year (1-365), minute-of-day,
height in tenths of a foot (int16, so 6.678 ft -> 67), and a High/Low flag.

Usage: python convert_tide_data.py > tide_data_2026.h
"""
import json
import datetime

with open("noaa_2026_raw.json") as f:
    data = json.load(f)

preds = data["predictions"]

rows = []
for p in preds:
    dt = datetime.datetime.strptime(p["t"], "%Y-%m-%d %H:%M")
    day_of_year = dt.timetuple().tm_yday
    minute_of_day = dt.hour * 60 + dt.minute
    height_tenths = round(float(p["v"]) * 10)
    is_high = 1 if p["type"] == "H" else 0
    rows.append((day_of_year, minute_of_day, height_tenths, is_high))

print(f"// NOAA CO-OPS tide predictions for 2026, station 9410230 (La Jolla, CA).")
print(f"// Generated by tools/tide_data/convert_tide_data.py from noaa_2026_raw.json")
print(f"// ({len(rows)} events). Columns: day-of-year(1-365), minute-of-day(0-1439),")
print(f"// height in tenths of a foot (signed), isHigh(1=High,0=Low).")
print(f"#define TIDE_EVENT_COUNT {len(rows)}")
print("struct TideEvent { uint16_t dayOfYear; uint16_t minuteOfDay; int16_t heightTenths; uint8_t isHigh; };")
print("static const TideEvent TIDE_EVENTS_2026[TIDE_EVENT_COUNT] = {")
for i, (doy, mod, ht, ih) in enumerate(rows):
    end = "," if i < len(rows) - 1 else ""
    nl = "\n" if (i + 1) % 6 == 0 else ""
    print(f"{{{doy},{mod},{ht},{ih}}}{end}", end=" " + nl)
print()
print("};")
